// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package storage

//go:generate go run -mod=mod entgo.io/ent/cmd/ent generate ./ent/schema
