// Code generated by Fabrica. DO NOT EDIT manually.
// This is a stub file created during init to prevent import errors.
// It will be replaced when Ent generates the real schema code.

package ent

// Placeholder to prevent import errors - will be replaced by Ent-generated code
