// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// NOTE: This file is a template without Go template syntax because it provides
// a generic, reusable Ent schema that works for all Fabrica projects without
// customization. It must be generated into each project because Ent's code
// generator (go generate) requires schemas to be present locally to generate
// the type-safe database client code.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// Annotation holds the schema definition for resource annotations.
type Annotation struct {
	ent.Schema
}

// Fields of the Annotation.
func (Annotation) Fields() []ent.Field {
	return []ent.Field{
		field.String("key").
			NotEmpty().
			MaxLen(253).
			Comment("Annotation key"),
		field.String("value").
			Comment("Annotation value (can be arbitrary length)"),
	}
}

// Edges of the Annotation.
func (Annotation) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("resource", Resource.Type).
			Ref("annotations").
			Unique().
			Required(),
	}
}

// Indexes of the Annotation.
func (Annotation) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("key"),
	}
}
